apiVersion: v1
kind: Service
metadata:
  name: backend-blue
  namespace: optiagent-prod
  labels:
    app: backend
    color: blue
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: backend
    color: blue
---
apiVersion: v1
kind: Service
metadata:
  name: backend-green
  namespace: optiagent-prod
  labels:
    app: backend
    color: green
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: backend
    color: green
---
apiVersion: v1
kind: Service
metadata:
  name: backend-active
  namespace: optiagent-prod
  labels:
    app: backend
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: backend
    color: blue