apiVersion: v1
kind: Service
metadata:
  name: frontend-blue
  namespace: optiagent-prod
  labels:
    app: frontend
    color: blue
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: frontend
    color: blue
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-green
  namespace: optiagent-prod
  labels:
    app: frontend
    color: green
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: frontend
    color: green
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-active
  namespace: optiagent-prod
  labels:
    app: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: frontend
    color: blue