apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: optiagent-prod
  labels:
    app: frontend
    app.kubernetes.io/name: optiagent
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: frontend